### ISSUE TITLE
Extra prompt at the end of the output

### ISSUE THREAD

**Issue by netixx** [scrapli/scrapligo#100]
Hello,

While testing a juniper device (finding the issue requiring to pass `options.WithNetconfForceSelfClosingTags(),`).

I get the following `r.Result` (only the end, for brevity):
```
</configuration>
</nc:data>
</nc:rpc-reply>
]]>]]>
```
(note that there is not newline after the prompt)

It seems to me that this shouldn't be the case. During my other tests, the output was only the XML. One of the difference between my previous tests is that this device only supports netconf 1.0 (I guess there is something different with the 1.0 code path).

**Comment by carlmontanari** [comment]
yeah, looks like it doesn't get stripped out of 1.0 payloads somewhere as it shows up like this in the unit tests too. 

fix [here](https://github.com/scrapli/scrapligo/pull/102/files), lemme know if that sorts it and will merge.

**Comment by netixx** [comment]
This branch fixes it for me:
```
</configuration>
</nc:data>
</nc:rpc-reply>

```
(note that there is a newline at the end, which isn't there with netconf1.1)

**Comment by carlmontanari** [comment]
ah yeah I moved the trim, will poke that again tonight/this weekend and re-trim it. I dont think it should matter much since loading up the xml should still be good but yea, better to be consistent! Thanks for raising this one @netixx !

**Comment by carlmontanari** [comment]
ok cool, added that extra trim and re-gen'd the test output. should be good to go! let me know and I'll get this merged!

thanks again @netixx !

**Comment by carlmontanari** [comment]
think this should be cool, going to merge that other pr now! thanks for raising this!
