### ISSUE TITLE
options.WithAuthPrivateKey() is not used by system transport

### ISSUE THREAD

**Issue by netixx** [scrapli/scrapligo#103]
The private key given by  `options.WithAuthPrivateKey()` is not used when using `options.WithTransportType("system")`.

It's used correctly with the standard transport, but there is not code implemented in system transport to use it (in `buildOpenArgs`).

Is that voluntary ? In this case I think it should be mentionned in the docs.
Else we need to extend the openArgs with `["-i", t.SSHArgs.PrivateKeyPath]`. I can submit a PR if you like.

**Comment by carlmontanari** [comment]
Yeah pr welcome. Standard transport is super bare bones right now.

**Comment by carlmontanari** [comment]
I said standard transport because I clearly cant read :) either, way, thanks for the PR -- just merged it, closing this out!
