### ISSUE TITLE
forceSelfClosingTags may return empty data

### ISSUE THREAD

**Issue by netixx** [scrapli/scrapligo#105]
Hello,

While testing get-operationnal queries on a juniper device that uses netconf 1.0, I was getting timeouts... so I looked around in the debugger and found out that the forceSelfClosingTags (which needs to be used with juniper because of a bug), erases the query alltogether.

See the following MWP (I copied the forceSelfClosingTags function and hard-coded the pattern):
```golang
package main

import (
	"fmt"
	"regexp"
)

func main() {
	req := `
	<?xml version="1.0" encoding="UTF-8"?><rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="101"><get><filter type="subtree">
	<routing-policy xmlns="http://openconfig.net/yang/routing-policy"></routing-policy>
	</filter></get></rpc>]]>]]>
	`
	print("filter")
	print(req)
	print("self-close")
	print(string(forceSelfClosingTags([]byte(req))))
}

func forceSelfClosingTags(b []byte) []byte {

	emptyTagIdxs := regexp.MustCompile(`<(\w+)></\w+>`).FindAllSubmatchIndex(b, -1)

	var nb []byte

	for _, idx := range emptyTagIdxs {
		// get everything in b up till the first of the submatch indexes (this is the start of an
		// "empty" <thing></thing> tag), then get the name of the tag and put it in a self-closing
		// tag.
		nb = append(b[0:idx[0]], fmt.Sprintf("<%s/>", b[idx[2]:idx[3]])...) //nolint: gocritic

		// finally, append everything *after* the submatch indexes
		nb = append(nb, b[len(b)-(len(b)-idx[1]):]...)
	}

	return nb
}
```

and it's output:
```
filter
        <?xml version="1.0" encoding="UTF-8"?><rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="101"><get><filter type="subtree">
        <routing-policy xmlns="http://openconfig.net/yang/routing-policy"></routing-policy>
        </filter></get></rpc>]]>]]>
        self-close                                                                                                                                                                                          
```

It seems to me that the pattern is too restrictive. A self-closing tag may contain any valid attributes.

I've experimented with this replace function instead (with some success):
```golang
func forceSelfClosingTags(b []byte) []byte {

	cleanStr := regexp.MustCompile(`<([^>/]+?)>\s*</[\w-]+>`).ReplaceAllString(string(b), "<$1/>")

	return []byte(cleanStr)
}
```

**Comment by hellt** [comment]
@netixx when you say `with some success`, was this replace function failing at some requests still?

**Comment by carlmontanari** [comment]
> It seems to me that the pattern is too restrictive. A self-closing tag may contain any valid attributes.

Yeah, cool, makes sense to me.

> @netixx when you say with some success, was this replace function failing at some requests still?

Defo curious the answer to this :D I'm happy to take a look and get a PR merged for this if ya come up with a solution that you are happy with and is working 100%! It would be great if we could get some basic unit tests around this too just so there isn't a regression here as this feels like one I would 100000% forget about and accidentally change at some point :)

**Comment by carlmontanari** [comment]
Just bumping this one back up! I think it makes sense and I'm happy to get this pattern updated, but I'm not sure all the cases we need to cover. Maybe even just having some example outputs we can dump into regex101 and mess about with would be enough for me to take it from here if you're not able to get a pr together.

Thanks ya'll!

Carl

**Comment by hellt** [comment]
Hi @carlmontanari 
I wanted to revive this, and I first started by creating a few regex101 examples comparing the two approaches. It is indeed valid to have a self closing tag for an element which has attributes (as verified with a [validator](https://www.w3schools.com/xml/xml_validator.asp)), e.g.

```
<elem some=value />
```

## 1 Original approach
In the original approach we have a trivial regexp that is indeed only capable of force self-closing on tags that do not have any attributes - https://regex101.com/r/wKlysd/1

## 2 Proposed approach
@netixx The proposed approach didn't work out for a simple set if XML blobs I used, therefore I had to tweak it a little bit as shown here https://regex101.com/r/rmsS2E/2 (pay attention to the substitution pane where the original XML blob gets transformed)

@carlmontanari I can write some tests to see if that re works, but have a look at it first.

**Comment by carlmontanari** [comment]
Awesome, thanks for picking this up @hellt !! Yeah the proposed approach sounds good to me, let's do it :D

**Comment by netixx** [comment]
Hello, sorry for being so late to the party...

By *with some success*, I meant that I tested it on the one device that was giving me trouble originally and that's it :)

It's a go for @hellt better regex for me as well!

**Comment by carlmontanari** [comment]
Hah cool, thanks @netixx ! I think Roman mentioned getting this sorted out is somewhere on his todo list so we should have this sorted in a little bit!

**Comment by carlmontanari** [comment]
Boom, Roman is the man, closing and wrapping this up in #114!
