### ISSUE TITLE
Calling transport.Close() for standard ssh does not close the TCP connection

### ISSUE THREAD

**Issue by mayuresh82** [scrapli/scrapligo#106]
Not sure whether this is intentional, but calling `Close()` on the standard ssh transport only closes the session and not the underlying TCP connection

https://github.com/scrapli/scrapligo/blob/main/transport/standard.go#L207

This means that for a long lived service that may need to open and close netconf sessions repeatedly, a queue of tcp connections continue to build up on the router and eventually hits the max connection limit and then everything explodes. 

The fix is to also close the underlying ssh client i.e 
```
err := t.client.Close()
```
I can send a PR for this  since I dont see any reason why you would want to keep a tcp connection open like that when a netconf driver is `Close()d`

**Comment by carlmontanari** [comment]
Hey @mayuresh82 yeah just an oversight- pr definitely welcome! Thanks!

**Comment by carlmontanari** [comment]
will be taking a look at pr hopefully very shortly, if not this weekend! will close this out and follow up in pr! thanks again @mayuresh82 !
