### ISSUE TITLE
Goroutine leak in channel.read() 

### ISSUE THREAD

**Issue by mayuresh82** [scrapli/scrapligo#107]
When this library is used in a long lived service, channel.read() can leak when the underlying transport is closed.

https://github.com/scrapli/scrapligo/blob/main/transport/standard.go#L207

When `c.t` is closed, the error received from `c.t.Read()` is `io.EOF` which needs to be checked for and then we need to return right away instead of passing this down the Err channel. 
I can send a PR for this fix.

**Comment by carlmontanari** [comment]
Going to close this and follow up in the pr! Thanks a bunch!
