### ISSUE TITLE
v1Dot1Caps has v1.0 format ?

### ISSUE THREAD

**Issue by netixx** [scrapli/scrapligo#120]
I am having issue retrieving the running-config from Cisco devices.

It seems they are closing the connection just after receiving the client capabilities.

We also use scrapli (which is working on those devices), so I was able to compare the payloads,
scrapli sends:
```
#167\n<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="101"><get-config><source><running/></source></get-config></rpc>\n##
```

scrapligo send the `v1Dot1Caps`, which is 
```
<?xml version="1.0" encoding="utf-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
     <capabilities>
         <capability>urn:ietf:params:netconf:base:1.1</capability>
     </capabilities>
</hello>]]>]]>
```

The devices only support netconf version 1.1.
Here is an example of the server capabilities (we are running Cisco IOS-XR version 7.5.2):
```
 <capabilities>
  <capability>urn:ietf:params:netconf:base:1.1</capability>
  <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
  <capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability>
  <capability>urn:ietf:params:netconf:capability:validate:1.1</capability>
  <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.1</capability>
  <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
  <capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
  <capability>http://cisco.com/ns/yang/Cisco-IOS-XR-infra-ceredundancymib-cfg?module=Cisco-IOS-XR-infra-ceredundancymib-cfg&amp;revision=2019-04-05</capability>
  <capability>http://cisco.com/ns/yang/Cisco-IOS-XR-um-attestation-cfg?module=Cisco-IOS-XR-um-attestation-cfg&amp;revision=2020-09-10</capability>
  <capability>http://cisco.com/ns/yang/Cisco-IOS-XR-um-aaa-task-user-cfg?module=Cisco-IOS-XR-um-aaa-task-user-cfg&amp;revision=2021-01-05&amp;features=pslib_check_password</capability>
  <capability>http://cisco.com/ns/yang/Cisco-IOS-XR-um-clock-cfg?module=Cisco-IOS-XR-um-clock-cfg&amp;revision=2020-07-07</capability>
  <capability>http://cisco.com/ns/yang/Cisco-IOS-XR-infra-tc-oper?module=Cisco-IOS-XR-infra-tc-oper&amp;revision=2020-07-26</capability>
...
 </capabilities>
```

**Comment by netixx** [comment]
Turns out I was completely wrong :) I confused the capabilities and the RPC calls in the logs.

Here the the channel log for python (truncated for brevity):
```
Password: 
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
 <capabilities>
  <capability>urn:ietf:params:netconf:base:1.1</capability>
  <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
  <capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability>
  <capability>urn:ietf:params:netconf:capability:validate:1.1</capability>
  <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.1</capability>
  <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
  <capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
...
 </capabilities>
 <session-id>2974823397</session-id>
</hello>
]]>]]>
<?xml version="1.0" encoding="utf-8"?>
    <hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
        <capabilities>
            <capability>urn:ietf:params:netconf:base:1.1</capability>
        </capabilities>
</hello>]]>]]>
#167
<?xml version='1.0' encoding='utf-8'?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="101"><get-config><source><running/></source></get-config></rpc>
##

#223
<?xml version="1.0"?>
<rpc-reply message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
 <data>
  <fpd xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-fpd-infra-cfg">
   <auto-upgrade>enable</auto-upgrade>
  </fpd>

#868
  <call-home xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-call-home-cfg">
   <vrf>VRF_MGMT</vrf>
   <active></active>
...
 </data>
</rpc-reply>

##
```

Here is for scrapligo:
```
Password: 

<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
 <capabilities>
  <capability>urn:ietf:params:netconf:base:1.1</capability>
  <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
  <capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability>
  <capability>urn:ietf:params:netconf:capability:validate:1.1</capability>
  <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.1</capability>
  <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
  <capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
...
 </capabilities>
 <session-id>716169560</session-id>
</hello>
]]>]]><?xml version="1.0" encoding="utf-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
     <capabilities>
         <capability>urn:ietf:params:netconf:base:1.1</capability>
     </capabilities>
</hello>]]>]]>
```
They match :) 

Reading this: https://www.rfc-editor.org/rfc/rfc6242#section-4.1
> [4.1](https://www.rfc-editor.org/rfc/rfc6242#section-4.1).  Framing Protocol
> The previous version of this document defined the character sequence  "]]>]]>" as a message separator, under the assumption that it could not be found in well-formed XML documents.  However, this assumption is not correct.  It can legally appear in XML attributes, comments, and processing instructions.  In order to solve this problem, and at the same time be compatible with existing implementations, this document defines the following framing protocol.  

> The <hello> message MUST be followed by the character sequence ]]>]]>.  Upon reception of the <hello> message, the receiving peer's  SSH Transport layer conceptually passes the <hello> message to the  Messages layer.  If the :base:1.1 capability is advertised by both peers, the chunked framing mechanism (see [Section 4.2](https://www.rfc-editor.org/rfc/rfc6242#section-4.2)) is used for the remainder of the NETCONF session.  Otherwise, the old end-of-message-based mechanism (see [Section 4.3](https://www.rfc-editor.org/rfc/rfc6242#section-4.3)) is used.  

So all is good on this front (sorry :) ).


However....

I investigated this issue because the device was closing the connection (I got and "invalid argument" error from the socket).

I compared the message that both python and go sent:
for go, I used the debugger, since the output is not logged because of the socket error. This is the value of `b` at line 66 of rpc.go:
```
"#175\n<?xml version=\"1.0\" encoding=\"UTF-8\"?><rpc xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\" message-id=\"101\"><get-config><source><running/></source></get-config></rpc>\n##"
```

for python, I used the channel log:
```
#167
<?xml version='1.0' encoding='utf-8'?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="101"><get-config><source><running/></source></get-config></rpc>
##
```

As you can see, the message are the same, except that the length is wrong in the case of go (assuming \" resolves to ").

This is because `ForceSelfClosingTags` does not update the length of the message in the framing. I think there should be a option in the serializer to force the self-closing tags, instead of doing it with a regex afterwards... or calculate the length after applying the force closing tags. I'll open another issue for that...

Regarding my original issue, I still don't get why the socket is closed just after sending the client capabilities. I am not able to reproduce the behavior using a manual session...

**Comment by carlmontanari** [comment]
> Regarding my original issue, I still don't get why the socket is closed just after sending the client capabilities. I am not able to reproduce the behavior using a manual session... 

This is troubling! can you try with `standard` transport as well (if you are not using it already -- otherwise try `system` :D) to see if it happens with both transports?

**Comment by carlmontanari** [comment]
> I got and "invalid argument" error from the socket

is this something you are seeing on the device logs or elsewhere? could you try the latest main and also with the opposite transport plugin if you get a chance?

I dont *think* it has to do with [this commit](https://github.com/scrapli/scrapligo/commit/4f8a034c0f278cde894d9bd391c26d276de2503c) but it may be possible... was your program doing just open, get config, close? if yes, its possible we blocked way way way too long on the force close (fixed in that commit) and then the device raised some socket error to just get rid of the connection... pure speculation at this point but obviously wanna get that sorted out if we can!

**Comment by netixx** [comment]
Ok, so I took a look again at my script...
Turns out I was doing `Close` before the `GetConfig`...

**Comment by carlmontanari** [comment]
😅 that'll do it -- glad things are workin!
