### ISSUE TITLE
length of string in commands []string led SendCommands panic

### ISSUE THREAD

**Issue by glenn914** [scrapli/scrapligo#138]
I have tried many times ,found that if the length of of string in commands []string greater than 56 will occur error like below:
err TimeoutError: channel timeout sending input to device.

for example :
(length 56 can get result from device)
show clock xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
(length 57 can't get result from device)
show clock xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by garygagaga** [comment]
I also find the issue,here is my demo:

`package main

import (
	"fmt"
	"github.com/scrapli/scrapligo/driver/options"
	"github.com/scrapli/scrapligo/platform"
	"time"
)

func main() {
	p, err := platform.NewPlatform(
		"huawei.yaml", "192.168.0.100",
		options.WithAuthUsername("admin"),
		options.WithAuthPassword("admin"),
		options.WithAuthNoStrictKey(),
		options.WithTransportType("standard"),
		options.WithTimeoutOps(10*time.Second),
		options.WithPort(22))
	if err != nil {
		fmt.Println("1111")
		fmt.Println(err)
	}
	d, err := p.GetNetworkDriver()
	if err != nil {
		fmt.Println("2222")
		fmt.Println(err)
	}
	err = d.Open()
	if err != nil {
		fmt.Println("4444")
		fmt.Println(err)
	}
	err = d.OnOpen(d)
	if err != nil {
		fmt.Println(err)
		return
	}
	r, err := d.SendCommand("#11111111112222222222333333333344444444445555555555666")
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(r.Result)
	d.Close()
}
`
the result was normal:
[root@netdev scrapligo_test]# go build
[root@netdev scrapligo_test]# ./scrapligo_test

[root@netdev scrapligo_test]#

but when i put one more character in command like "#111111111122222222223333333333444444444455555555556666"
there's panic:
[root@netdev scrapligo_test]# go build
[root@netdev scrapligo_test]# ./scrapligo_test
errTimeoutError: channel timeout sending input to device
[root@netdev scrapligo_test]#

**Comment by carlmontanari** [comment]
as mentioned before, you need to disable terminal width. `screen-length 0 temporary` probably like in the scrapli community Huawei platform [here](https://github.com/scrapli/scrapli_community/blob/main/scrapli_community/huawei/vrp/sync_driver.py)

**Comment by glenn914** [comment]
I tried cisco platform ，it's normal:

[root@gary scrapligo_test]# cat main.go
package main

import (
        "fmt"
        "github.com/scrapli/scrapligo/driver/options"
        "github.com/scrapli/scrapligo/platform"
)

func main() {
        p, err := platform.NewPlatform(
                "cisco_iosxe", "10.103.158.8",
                options.WithAuthUsername("cisco"),
                options.WithAuthPassword("admin123"),
                options.WithAuthNoStrictKey(),
                options.WithTransportType("standard"),
                options.WithPort(22))
        if err != nil {
                fmt.Println("1111")
                fmt.Println(err)
        }
        d, err := p.GetNetworkDriver()
        if err != nil {
                fmt.Println("2222")
                fmt.Println(err)
        }
        err = d.Open()
        if err != nil {
                fmt.Println("4444")
                fmt.Println(err)
        }
        d.OnOpen(d)
        r, _ := d.SendCommand("#111111111122222222223333333333444444444455555555556666666666666666666666")
        //r.TextFsmParse()
        //s, _ := d.SendConfig("display interface brief")
        fmt.Println(r.Result)
        //fmt.Println(s.Result)
        d.Close()
}
[root@gary scrapligo_test]#
[root@gary scrapligo_test]#
[root@gary scrapligo_test]# go run main.go

[root@gary scrapligo_test]#
[root@gary scrapligo_test]#

let me do more research , thx for your reply!
