### ISSUE TITLE
failed to open driver: read /dev/ptmx: input/output error

### ISSUE THREAD

**Issue by zwiy** [scrapli/scrapligo#139]
Hi

I'm not sure if it's related to this: https://github.com/scrapli/scrapligo/pull/135

I wrote a small scrapligo application inside a vscode devcontainer `mcr.microsoft.com/devcontainers/go:0-1.20-bullseye`. It's running as it should.

But running it in an `alpine`, `ubuntu` or `golang` container doesn't work and ends up directly with this error message while opening the driver `Driver.open()`:
```
read /dev/ptmx: input/output error
```

Maybe somebody has a hint for me?
Thanks!

**Comment by hellt** [comment]
Maybe as a workaround you can use standard transport which doesn't use pty?

**Comment by zwiy** [comment]
Thanks for your fast response.
Where can I set/change the transport mode?

Currently I have something like that:

```
p, err := platform.NewPlatform(
	platformDefinitionPath,
	hostname,
	options.WithAuthNoStrictKey(),
	options.WithAuthUsername(username),
	options.WithAuthPassword(password),
	options.WithAuthSecondary(enablePassword),
)
if err != nil {
	return nil, fmt.Errorf("failed to create platform: %w", err)
}

d, err := p.GetNetworkDriver()
if err != nil {
	return nil, fmt.Errorf("failed to fetch generic driver from the platform: %w", err)
}

...

```

**Comment by zwiy** [comment]
Nice 🚀 . Thanks for your help. It runs now also in an `alpine` image.
