### ISSUE TITLE
Exposing NETCONF server capabilities

### ISSUE THREAD

**Issue by karimra** [scrapli/scrapligo#140]
Hi,

I'm trying to write a netconf client using the scraligo driver.
Looked through the code and it seems like the server capabilities are not exposed, 
there is a `ServerHasCapability(s string) bool` function which requires prior knowledge of the possible capabilities a server might support.
It would be useful to have a `ServerCapabilities() []string` function that returns a copy of `d.serverCapabilities`.
If this is ok with you I can create a PR adding that function.

**Comment by carlmontanari** [comment]
Ah! Yeah sounds great! I heard a whisper about the new project :) would love to get involved too if there’s anything I can do or any changes I can make here to help things along! Maybe we can chat on discord or whatever too if that’s easier!

**Comment by karimra** [comment]
Thanks, yes happy to discuss I could use someone with more NETCONF knowledge.

**Comment by carlmontanari** [comment]
merged, thanks a bunch!
