### ISSUE TITLE
Add option to read exact input

### ISSUE THREAD

**Issue by moubella** [scrapli/scrapligo#153]
We're implementing a driver using **scrapligo** in our app, and currently in our tests, we're asserting the exactitude of the input commands sent to the device.

As of now we didn't find a way to correctly assert against the exact input, since [ReadUntilInput](https://github.com/scrapli/scrapligo/blob/main/channel/read.go#L103) reads bytes until the input is 'seen' in the output.

**Example of correct input in our test:**
"configure terminal"

**Example of input that should fail in our use case:**
"AAAAAAAconfigure terminal".

Since the string "configure terminal" is seen in the input, the test does not fail.

Can we read the exact input using scrapligo? 

Thanks in advance.

**Comment by carlmontanari** [comment]
pretty sure you are just looking for the [strip prompt option](https://github.com/scrapli/scrapligo/blob/main/driver/opoptions/channel.go#L14).

`ReadUntilInput` is already doing what you are asking for -- it reads until the given input is seen (literally `bytes.Contains`).

When used w/ the `SendInput` or higher level `SendCommand(s)/Config(s)` things read until a prompt, then writes your input, then reads up to it, then sends return, then reads till the next prompt, and returns all the output (w/ or w/out prompt stripped based on your preference ofc). so if you are going that route then you can use strip prompt to get rid of prompt.

if you literally just want the input checked (what is the use case btw?) and are bypassing the `SendInput`/`SendCommand(s)` stuff then I think you can just call `ReadUntilPrompt` to basically drain data out of the internal read queue, then write whatever you want (channel.Write) then `ReadUntilInput`.

**Comment by moubella** [comment]
I think I wasn't clear enough. We are indeed using `SendCommand` to send a list of commands. We happened to observe a problem with a test that should fail:
We send a list of commands line by line (without commas), and in our tests, we 'expect' the output to contain commas. The test passes in this case.

After closely examining the code, we realized that `ReadUntilInput` is not suitable for our scenario since we absolutely need to test the exactitude of the input.
So  we were wondering if there's an alternative with which we can achieve this.

**Comment by carlmontanari** [comment]
`since we absolutely need to test the exactitude of the input` im confused because `ReadUntilInput` is literally calling `bytes.Contains` so it is for sure checking for your input (exactly). this is one of the central points of scrapli(go) in general: we never ever send a return until we've read exactly the input. (side note: this is getting a little more lax soon, see #151 if interested, but even then there is an option to use the current/historical explicit option).

If for whatever reason that doesn't work for you you can use the channel `Read` and `Write` methods w/out the "higher level" `SendInput`/`SendCommand(s)` though -- all that stuff is exposed/public just in case people wanna do something "non standard".

**Comment by moubella** [comment]
Hey again @carlmontanari,
Here is a [**gist**](https://gist.github.com/moubella/e6fdc1fe27bd439140b8f6ec733d06bf) detailing exactly what we want to achieve:

Basically, we'd like for a way to test the commands we are generating against a known valid output, not just as subset but as an exact match (nothing less, nothing more). Do you know if this is possible ?

Thank you

**Comment by moubella** [comment]
@carlmontanari, Thanks for your response.
We decided to go with a custom buffer on which we write the commands we send to the device, and we assert against those commands (instead of asserting against the values written on the transport file. 

This issue can be closed.

Regards,
