### ISSUE TITLE
Support modifying TimeoutSocket using standard transport

### ISSUE THREAD

**Issue by patrickfnielsen** [scrapli/scrapligo#155]
Right now it seems there is no way to modify the dial timeout when using standard transport:
https://github.com/scrapli/scrapligo/blob/0ae361300f6ef3f3d402c59567af66fb671ba6eb/transport/standard.go#L147

There is `WithTimeoutOps` for channel operations, but that does not modify the dial timeout in anyway as far as I can see.
I suggest we add an option to allow modifying dial timeout, as the default might not always be desirable. 

I'll be happy to help with a PR if you needed :)

**Comment by carlmontanari** [comment]
well would you look at that! hehe... my bad! yeah we should expose that timeout socket with an option somewhere around [here](https://github.com/scrapli/scrapligo/blob/0ae361300f6ef3f3d402c59567af66fb671ba6eb/driver/options/transport.go) (which as a side note is a lame place to put *transport* options but.... I guess my thinking at the time was to put them all in one place... so here we are 🤣 )

a pr would be most welcome, thank you @patrickfnielsen

**Comment by carlmontanari** [comment]
closing, can wrap up in #155 -- thanks again!
