### ISSUE TITLE
unsupported error on open driver

### ISSUE THREAD

**Issue by arphillips06** [scrapli/scrapligo#158]
Hi, 

I'm trying to learn automation in go, I'm a relatively newbie at programming so might be missing something obvious. 

I'm trying to run the "generic_driver" example against a vMX device I have in GNS3. The device is reachable from my Windows PC, I'm using go version 1.21 and VScode as my IDE. 

When I run the example (after updating the hostname) all I get is;

```failed to open driver; error: unsupported```

I'm not sure if I've not installed something I needed to? The code compiles and runs ok so I thought I'd installed everything I needed to but it might not be the case. 

Thanks

**Comment by carlmontanari** [comment]
Use standard transport type [here](https://github.com/scrapli/scrapligo/blob/main/driver/options/generic.go#L14) or don’t use windows. Scrapli wraps /bin/ssh with the default transport.

Please use discussions or ask on discord for non bug/feature related things.
