### ISSUE TITLE
Support for changing the prompt temporariliy during a session

### ISSUE THREAD

**Issue by netixx** [scrapli/scrapligo#160]
Hello :),

I need to run shell commands on ios-xr, that means entering the "run" command, getting into the linux shell.

I tried with :
```
shellPattern := regexp.MustCompile(`(?im)^\[[^]]+\]\$\s*$`)
shellResp, err :=  d.SendCommands(
  append([]string{"run", "pwd"}),
  options.WithPromptPattern(shellPattern),
)
```

but it doesn't seem to be applied. I think `PrompPattern` is a channel option only (and not an operation option) ?

Is it possible to change the prompt during the same session ?
In my case, changing it at the transport level wouldn't work because we still land on the normal NOS shell as we connect.

**Comment by netixx** [comment]
I was able to make it work rolling my own option:
```
func WithInterimPromptPattern(p *regexp.Regexp) util.Option {
	return func(o interface{}) error {
		c, ok := o.(*channel.OperationOptions)

		if !ok {
			return util.ErrIgnoredOption
		}

		c.InterimPromptPatterns = []*regexp.Regexp{p}

		return nil
	}
}
```

However I think that `InterimPromptPatterns` should be initialized inside the NewOperation, so that we can do `append` in the option.

Also, maybe there should be a simpler way to do that (like a switch-case in `WithPromptPattern` that works for operations.Channel also) ?

**Comment by netixx** [comment]
Custom platform looks like the right solution indeed. Never used it in go yet :) 

> If im following correctly -- maybe the option can just accept variadic? that would be no public api change (basically), and then could still append as many patterns as ya want?

My issue here is that the `c.InterimPromptPatterns` array is not initialized anywhere, so in my `WithInterimPromptPattern` function I cannot do "append" to `c.InterimPromptPatterns`. Well I can but it will crash :)

**Comment by carlmontanari** [comment]
hah, well that makes a lot of sense :P ok will investigate this weekend and get something sorted out! thanks for all the help!

**Comment by netixx** [comment]
BTW I opened a PR to add the run shell to the list of privilege levels.
I figured anyone could use it, I'll let you decide if it's indeed the case :)

**Comment by carlmontanari** [comment]
> BTW I opened a PR to add the run shell to the list of privilege levels.
I figured anyone could use it, I'll let you decide if it's indeed the case :)

saw it, and merged! thank you!

> My issue here is that the c.InterimPromptPatterns array is not initialized anywhere, so in my WithInterimPromptPattern function I cannot do "append" to c.InterimPromptPatterns. Well I can but it will crash :)

I may be making myself even more confused, but since it will be nil from the get go (because not "initialized") you should still be able to append to that just fine? am I missing something else here?

```go
type OperationOptions struct {
	InterimPromptPatterns []*regexp.Regexp
}

func main() {
	o := &OperationOptions{}

	o.InterimPromptPatterns = append(o.InterimPromptPatterns, regexp.MustCompile(`foo`))

	fmt.Println(o.InterimPromptPatterns)
}
```

^ works ok no? sorry I keep coming back to this long enough away that I lose all context and then get more confused :D hopefully above makes sense / is ok and we are good to go!

**Comment by netixx** [comment]
yes, my bad appending to a nil slice is legit in go :)

you are 100% right!!
