### ISSUE TITLE
Unable to read from /dev/ptmx

### ISSUE THREAD

**Issue by vincentbernat** [scrapli/scrapligo#168]
Hey!

With this simple test program:

```go
package main

import (
	"log"

	"github.com/scrapli/scrapligo/driver/options"
	"github.com/scrapli/scrapligo/platform"
)

func main() {
	p, err := platform.NewPlatform(
		"nokia_srl", "127.0.0.1",
		options.WithAuthNoStrictKey(),
		options.WithAuthUsername("admin"),
		options.WithAuthPassword("NokiaSrl1!"),
		options.WithPort(57401),
	)
	if err != nil {
		log.Fatalf("NewPlatform() error:\n%+v", err)
	}
	d, err := p.GetNetworkDriver()
	if err != nil {
		log.Fatalf("GetNetworkDriver() error:\n%+v", err)
	}
	err = d.Open()
	if err != nil {
		log.Fatalf("Open() error:\n%+v", err)
	}
	defer d.Close()
	r, err := d.SendCommand("show version")
	if err != nil {
		log.Fatalf("SendCommand(show version) error:\n%+v", err)
	}
	log.Printf(
		"sent command '%s', output received (SendCommand):\n %s",
		r.Input,
		r.Result,
	)
}
```

And a Docker container with SRLinux running and 57401 mapped to 22. I get:

```
 00:10 ❱ go run main.go
2024/01/07 00:10:54 Open() error:
read /dev/ptmx: input/output error
exit status 1
```

SSH works fine:

```
 00:11 ❱ ssh admin@127.0.0.1 -p 57401 "show version"
admin@127.0.0.1's password:
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Hostname             : e8a4de3b8e0a
Chassis Type         : 7220 IXR-D3L
Part Number          : Sim Part No.
Serial Number        : Sim Serial No.
System HW MAC Address: 6A:03:02:FF:00:00
Software Version     : v23.7.1
Build Number         : 163-gd408df6a0c
Architecture         : x86_64
Last Booted          : 2024-01-06T22:19:59.338Z
Total Memory         : 64214175 kB
Free Memory          : 52309761 kB
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by carlmontanari** [comment]
Hey there!

This popped up once before [here](https://github.com/scrapli/scrapligo/issues/139) I believe -- short fix is to use standard transport (go crypto vs subprocess wrapper). Otherwise can probably mess with passing some other ssh flags to see (thinking -t or maybe its -T or two of them... can't recall off the top of my head!) to mess w/ pty things.

Would standard transport be ok fix for now?

**Comment by carlmontanari** [comment]
Or maybe there is some more reading things for future me to look at when I have some more time :) stuff like [this](https://github.com/creack/pty/issues/21) and [maybe this](https://github.com/fakegit/upterm/commit/0b9e460dbe3883a787945788939c015232d87ed3)

**Comment by vincentbernat** [comment]
I have tried to enable logging to debug more and discovered that I don't get a password when running the SSH command manually:

```

**Comment by vincentbernat** [comment]
Switching to standard transport works.

**Comment by carlmontanari** [comment]
can you see if adding `-tt` to your ssh command feels better? [here](https://github.com/scrapli/scrapli_netconf/blob/main/scrapli_netconf/transport/plugins/system/transport.py#L24-L32C35) is where that was sticking in my head from, wonder if its relevant? 

> Switching to standard transport works

ok cool. crappy "fix", but better than nothing :)

> Received disconnect from 127.0.0.1 port 57401:2: Too many authentication failures

too many auth failures feels bad, does that happen every time? wonder if the ssh server is just upset at something we're doing?

**Comment by vincentbernat** [comment]
In fact, because of `-F /dev/null`, this removes my `IdentitiesOnly yes` I am using to workaround problems like this, where some SSH servers do not like to receive too many key attempts. I have 14 keys in my agent. I would suggest to add this option to avoid using the SSH keys inside the agent without an explicit mention?

**Comment by carlmontanari** [comment]
we always use /dev/null for config unless you tell it not to -- you can pass an explicit config or have it lookup default config file paths with [these options](https://github.com/scrapli/scrapligo/blob/main/driver/options/transportssh.go#L41-L95)! that should sort that out for ya I think ya?

**Comment by hellt** [comment]
yeah I now as well having too many keys in my agent and got burnt by this as well

**Comment by vincentbernat** [comment]
Would it be OK to unconditionally add `-o IdentitiesOnly=true` before the configuration file?

**Comment by hellt** [comment]
I don't recall from the top of my head but I'd say more appropriate would be to set this ssh client option when we define the options for the platform

**Comment by carlmontanari** [comment]
yeah I think hope that these two options [here](https://github.com/scrapli/scrapligo/blob/99fee0b5035d24f4a48bb1c7e01f65bc92226b8b/driver/options/transportsystem.go#L24-L54) should give ya what you need to tune things to whatever is best for your environment. let us know if that works ok?

**Comment by hellt** [comment]
I had a brief look at it, and when we use the StandardTransport then you shouldn't have any issues with agent bombing the server with many keys, so this should be all good and also solving your problem with ptx mystique.
