### ISSUE TITLE
NetConf connection disconnect even though keepalive is sent from the server.

### ISSUE THREAD

**Issue by dau71** [scrapli/scrapligo#173]
**Requirement**

To keep the NetConf connection alive for as long as we can and identify when this connection is lost and reconnect without having to send a Netconf message within the timeout period.

**The problem:**

Using the standard transport, I am trying to keep the connection active but the connection is disconnected after the `ClientAliveInterval` time has passed. I also receive a malformed message from the NetConf server just before the disconnection but I have not sent any NetConf message to the server during this time.

e.g. Malformed message from the device
`<?xml version="1.0" encoding="UTF-8"?> <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"> <rpc-error> <error-type>rpc</error-type> <error-tag>malformed-message</error-tag> <error-severity>error</error-severity> <error-message>A message could not be handled because it failed to be parsed correctly.</error-message> </rpc-error> </rpc-reply>
`

Doing a tcpdump I can see the keep alive is sent from the server every 15 seconds which is also confusing as the settings on the server is 60 seconds. Is there anything in scrapligo that changes the `ServerAliveInterval` to 15 seconds?

e.g. code connecting to an Adtran SDX 6320 device.

```
func scrapliTestAdtran() {
	host := "<host>"
	username := "<username>"
	password := "<password>"

	d, err := netconf.NewDriver(
		host,
		options.WithAuthNoStrictKey(),
		options.WithAuthUsername(username),
		options.WithAuthPassword(password),
		options.WithPort(830),
		options.WithTransportType(transport.StandardTransport),
	)
	if err != nil {
		fmt.Printf("failed to create driver for %s; error: %+v\n", host, err)
		return
	}

	err = d.Open()
	if err != nil {
		fmt.Printf("Failed to open driver for %s; error: %+v\n", host, err)
		return
	}

	defer d.Close()

	for {
		filter := "<xpon><t-conts/></xpon>"
		resp, _ := d.Get(filter)

		fmt.Println(resp.Result)
		fmt.Println("***********************************************")
		time.Sleep(120 * time.Second)
	}
}
```

Thanks in advance.

**Comment by carlmontanari** [comment]
Hey @dau71 👋 

quickly checking the only timeout we set on standard transport is the "TimeoutSocket" (15s default) in the ssh client config [here](https://github.com/scrapli/scrapligo/blob/866008fb14c55a251aa89633cc70657b72f815c7/transport/standard.go#L144).

we *do* send serveraliveinterval but only in system transport -- so if anything is modifying that it would be in upstream crypto/ssh as far as I know.

as im not a standard transport user, if there are any tweaks we can make here to bring it more inline w/ feature parity of system transport while you're investingating this let us know as that would be great.

**Comment by carlmontanari** [comment]
hey @dau71 I'm going to go ahead and close this out for now - but would be great if you discovered anything else if ya can update us. feel free to reopen if you've got some more info we can work with to improve things! thanks!
