### ISSUE TITLE
WIDE enough terminal or `WithTerminalSize` option is needed

### ISSUE THREAD

**Issue by hellt** [scrapli/scrapligo#18]
Hi @carlmontanari 
Consider an SR Linux example (and Hua) where we need to increase the width of the allocated terminal to not wrap lines and thus keeping a consistent prompt detection.

I propose to consider either of those options:

1. make the default width large enough (256 chars instead of 40). This needs to be added to both standard and system transport 

2. To allow for users and custom drivers to set the width/height of a requested PTY I think a new option `WithTerminalSize` (or `WithPTYSize`) makes a lot of sense

**Comment by carlmontanari** [comment]
Good shout. Will try to get a PR together shortly for this... will also go back and retrofit python version to align w/ the values we set here to keep things in lock step!

**Comment by carlmontanari** [comment]
#20 is first hack at addressing this! lemme know what ya think!
