### ISSUE TITLE
unneeded field intialization in `buildGraphPrivilege`?

### ISSUE THREAD

**Issue by hellt** [scrapli/scrapligo#4]
Hi @carlmontanari 
Do you need to reinitilize the `d.PrivGraph` here
https://github.com/scrapli/scrapligo/blob/a31197a0902e9f1550999cf56a9af1c1350b417a/driver/network/privilege.go#L17

if you did this already here
https://github.com/scrapli/scrapligo/blob/a31197a0902e9f1550999cf56a9af1c1350b417a/driver/network/network.go#L35

**Comment by carlmontanari** [comment]
Yes and no I think....

In most cases I think that this is almost certainly duplicated effort.... in "normal" (python) scrapli though, and hopefully soon in scrapligo, users can "register" new configuration sessions. This "registration" process dynamically adds a privilege level of whatever the session name is, we then call the `UpdatePrivilegeLevels` method again. For just adding config sessions I guess there is no reason to reinitialize the `d.PrivGraph` but I guess its also possible that users may remove config sessions and such. So my thinking was just any time we hit this section of code we just start with a clean slate. Hopefully that makes sense? And perhaps more importantly is sane...?

**Comment by hellt** [comment]
ok, what about keeping `d.PrivGraph` in privilege function, but removing it from Driver struct as proposed here https://github.com/scrapli/scrapligo/pull/8 ?

**Comment by carlmontanari** [comment]
> ok, what about keeping `d.PrivGraph` in privilege function, but removing it from Driver struct as proposed here #8 ?

makes sense to me, merging shortly. will close this one out too!
