### ISSUE TITLE
It would be very nice to add a raw RPC method for the netconf driver

### ISSUE THREAD

**Issue by idqdq** [scrapli/scrapligo#54]
Hi Carl
I like scrapli very match, very appreciate your job :1st_place_medal: 
It is the number one toolkit for me in my network automation journey
Recently I've got a task to make a script that kills ipsec sessions from one Juniper SRX device
And I've made it just in a couple of minutes using the scraply_netconf library

But then I thought what if I want to hand over my script to some guys related to that Ipsec issues 
But they are working on windows platform and know nothing on python, venv, bash, etc

And then I remembered there is scrapligo project that does all that scrapli do but using golang
Seems it fits my needs. 
Unfortunately I almost don't know golang but the task is pretty simple so It is not that hard to do it on any language

This was intro and now back to the issue, 
actually there are two issues I've ran into with my task

I found out scrapligo has no RPC method I getting used to use with scrapli to perform raw rpc requests

as a workaround I took the method _d.BuildCommitElem()_  from payload.go file as a temlpate,
and replaced the _XMLName_ data with _XMLName xml.Name `xml:"clear-ike-security-association"`_
now It worked but seems like a routh hack and looks ugly

So this is the Issue:
Please, could you please add the RPC method like we all have in the python based scrapli_netconf lib?

Thanks
with best regards
Nikolay Ryzhkov

p.s the second issue I ran into is on the way :)

**Comment by carlmontanari** [comment]
Hey Nikolay -- I think this is a good idea. It will be a while till I get to it, but I will keep this open to remind me 😁

**Comment by carlmontanari** [comment]
Hey again Nikolay! Just opened a PR for this. Wasn't too hard but had to remember how all the netconf bits work 🙃 

Will close this and maybe you can chime in on the PR if that works for ya?

Thanks dude!

Carl
