### ISSUE TITLE
nil pointer dereference

### ISSUE THREAD

**Issue by networkop** [scrapli/scrapligo#64]
Not sure yet exactly what's causing it. Caught it when trying to apply EOS config twice (with slight modification on the second time)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x622ea7]

goroutine 1 [running]:
github.com/scrapli/scrapligo/driver/network.(*Driver).SendConfig(0xc0001266c0, {0xc000430780, 0x1cd}, {0xc00019fbc0, 0x1, 0x1})
        /home/mk/go/pkg/mod/github.com/scrapli/scrapligo@v0.1.2/driver/network/sendconfig.go:19 +0xc7
github.com/scrapli/scrapligo/cfg.(*EOSCfg).loadConfig(0xc000200930, {0xc000430780, 0xc00019fca0}, {0x0, 0x0}, 0xb0)
        /home/mk/go/pkg/mod/github.com/scrapli/scrapligo@v0.1.2/cfg/aristaeos.go:177 +0x1d3
github.com/scrapli/scrapligo/cfg.(*EOSCfg).LoadConfig(0xc000200930, {0xc000430000, 0xc00019fd68}, 0x8, 0x15)
        /home/mk/go/pkg/mod/github.com/scrapli/scrapligo@v0.1.2/cfg/aristaeos.go:234 +0x24f
github.com/scrapli/scrapligo/cfg.(*Cfg).LoadConfig(0xc0002c49a0, {0xc000430000, 0x1cd}, 0x3, {0x0, 0x0, 0x0})
        /home/mk/go/pkg/mod/github.com/scrapli/scrapligo@v0.1.2/cfg/base.go:421 +0x2cd
main.main()
        /home/mk/scrapli/main.go:115 +0x934
exit status 2
```

https://github.com/scrapli/scrapligo/blob/f016abc99e1872704b574feab21937ae1767ddb5/driver/network/sendconfig.go#L19

**Comment by carlmontanari** [comment]
Thanks for reporting this Michael! I'll try to dig in and see if I can reproduce and get to the bottom of it! I'll keep ya posted!

**Comment by carlmontanari** [comment]
I am *fairly* sure that this occurs when we hit the configuration session limit. I reproduced and got a similar panic after intentionally creating 5 config sessions (my vEOS instance at least has a 5 config session limit).  I'm calling it for today, but wanted to jot this note down. ive been meaning to add some "smarts" around this config session limit for eos, but I want to make sure whatever gets added/changed is as minimal as possible (so as to not add a bunch of eos specific code if at all possible).... will poke around on this in the next week or so and keep ya posted.

carl
