### ISSUE TITLE
Make scrapligo-netconf work with older nxos devices

### ISSUE THREAD

**Issue by tamasv** [scrapli/scrapligo#67]
Some nxos devices require 2 XML namespace attributes in the RPC element. ( see https://community.cisco.com/t5/network-management/netconf-get-config-error-wrong-document-namespaces-not-specified/td-p/3298323 )
It would be nice if we could define a second namespace while doing netconf operations with such devices.

According to my testing, defining the namespace in the raw filter query does not work. After the request, I'll get back a default hello reply and the device closes the connection. Sometimes, there is an RPC namespace missing error msg.

Request:
```
2022/03/09 15:19:05 write::localhost::10022::write: 
<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="101">
<get>
<filter type="subtree">
<show xmlns="http://www.cisco.com/nxos:1.0:nfcli">
<interface>
</interface>
</show>
</filter>
</get>
</rpc>]]>]]>
```
Reply
```
2022/03/09 15:19:05 debug::localhost::10022::read: <?xml version="1.0" encoding="utf-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
     <capabilities>
         <capability>urn:ietf:params:netconf:base:1.0</capability>
     </capabilities>
</hello>]]>]]>
```
Reply with error msg
```
022/03/09 15:19:03 debug::localhost::10022::read: <?xml version="1.0" encoding="ISO-8859-1"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="101">
  <rpc-error>
    <error-type>rpc</error-type>
    <error-tag>missing-attribute</error-tag>
    <error-severity>error</error-severity>
    <error-message>Wrong document: namespaces not specified</error-message>
    <error-info>
      <bad-element>rpc</bad-element>
    </error-info>
  </rpc-error>
</rpc-reply>
]]>]]>
```

**Comment by carlmontanari** [comment]
Seems like a reasonable addition -- I'd imagine some other platforms would want/expect more than one namespace too! I've not been doing a ton of netconf stuff lately so will probably take me a while to get back into it to check things out. If you are open to working on a PR that would be great too!

Thanks for raising this issue!

Carl

**Comment by tamasv** [comment]
I definitely would like to work on a PR! However, my golang knowledge and experience is limited.
Adding a SecondaryNamespace to the Message struct would be a straightforward solution and implement some new Option to change it, but as you mentioned, maybe other devices require different XML/message modifications.
What do you think about implementing Augments for netconf driver and refactoring all XML building operations ( Build*Elem ) to check if there is an augmented method, if not then use the current one?
This way, every specific driver should have the ability to change/influence how the messages are built. As far as I understand, everything after the build*elem uses interface{} ( except FinalizeAndSend param ), so it should not be a problem to use custom message struct for different device types.

**Comment by carlmontanari** [comment]
> What do you think about implementing Augments for netconf driver and refactoring all XML building operations ( Build*Elem ) to check if there is an augmented method, if not then use the current one?

I'm not 100% sure im following/am visualizing this to be honest! I think my first reaction (having not looked closely at the netconf bits in a while, so this could be totally a bad idea 😁 ) is just to reswizzle namespace field of the message struct to be a slice of string that we then handle however. 

> For example, CopyConfig would change from this

I don't want to replace arguments (like source/target in this example) with options - these are required fields (source/target for the copy operation in this case, but I'm referring to all the methods) and I'm not sure I'm tracking why that would need to be done? We can just add other option(s) to include the namespace bits no?

Hopefully those are coherent thoughts! Been a hectic week!

Carl

**Comment by tamasv** [comment]
> Hopefully those are coherent thoughts! Been a hectic week!
Absolutely!

Sorry, I misunderstood your reply about other platforms that would expect more namespaces. I thought that you suggest refactoring the netconf module for a more "general" approach.

Adding an extra field for the namespace could work, but what do you think would be the best way to handle namespace prefixes?
It seems, that golang's XML lib is somewhat limited when it comes to handling proper XML ns prefixes. ( https://github.com/golang/go/issues/9519 ).
If the user can define multiple namespaces, how much freedom should be given to customize the usage of the given namespace? 
Is it allowed to say, that I want X namespace to be the default namespace of the netconf msg?
If yes, then rpc and all other elements should be ns prefixed by default, or should the user be able to choose a prefix for the default netconf:base ns?

This example shows, that nxos ( according to the cisco forum ) expect the default NS to be a cisco specific one and netconf:base elements should be prefixed.
```
<nf:get-config
    xmlns:nf="urn:ietf:params:xml:ns:netconf:base:1.0"
    xmlns="http://www.cisco.com/nxos:7.3.1.D1.1.:urib">
    <nf:source>
        <nf:running/>
    </nf:source>
</nf:get-config>
```

**Comment by carlmontanari** [comment]
> Adding an extra field for the namespace could work, but what do you think would be the best way to handle namespace prefixes? 

To be honest I haven't seen any devices (till now) that this is an issue, so I hadn't thought about it :)

*If* we are to make any changes then I think the default behavior basically needs to be what it is today -- because that has worked for every device I have seen, and any other behavior would be governed by options provided presumably at driver creation (WithNetconfBaseNamespace, WithNetconfExtraNamespace or something like that?). 

To be honest getting any change made/merged with this may be an uphill battle as I dont have any nxos 7.x and I think that is probably not a super common platform. Thats not to say we can't make some changes/improvements, just that it will require some extra work and maybe access to something running 7.x so I can check it out first hand.

Carl

**Comment by carlmontanari** [comment]
Going to close this for now. I'm working on a big overhaul for scrapligo -- it won't include this, but may be easier to slot it in, so if there is interest we can reopen/rediscuss after the 1.0.0 release in the next few weeks/month or tow.

Carl

**Comment by carlmontanari** [comment]
this will hopefully be supported in scrapligo 2.0 -- see test [here](https://github.com/scrapli/scrapligo/blob/feat/scrapligo2.0/netconf/raw_rpc_test.go#L26-L33) -- I *think* this is, if not working now, close and can get the rest dialed in. basically there is the linked thing here where we can add additional namespaces, and then a base namespace prefix [here](https://github.com/scrapli/scrapligo/blob/feat/scrapligo2.0/options/netconf.go#L42) that should let us make rpcs like the example in that cisco blog post
