### ISSUE TITLE
Implement FortiOS Support

### ISSUE THREAD

**Issue by jwdevos** [scrapli/scrapligo#72]
Hi,

I would really like to have FortiOS support, to make scrapligo work with FortiGate firewalls. This support in scrapligo is also a dependency to make FortiGates work in Containerlab.

I will dig in to scrapligo myself to see if I can get started on building the FortiOS support, but it seemed like a good idea to create an issue first. Maybe others have insights to share as well.

Kind regards,
Jaap de Vos

**Comment by carlmontanari** [comment]
Hey Jaap! Sounds good.

Not sure [this](https://github.com/scrapli/scrapli_community/tree/master/scrapli_community/fortinet) will be of any help since its for the WLC thing, but maybe you can steal some patterns from here or something.

Let me know if you need a hand with anything!

Carl

**Comment by carlmontanari** [comment]
Going to close this for now. I'm working on a big overhaul for scrapligo --that will make adding platforms even easier (as in just a yaml file) so if there is interest we can reopen/rediscuss after the 1.0.0 release in the next few weeks/month or two.

Carl
