### ISSUE TITLE
Include the prompt in the results

### ISSUE THREAD

**Issue by kellerza** [scrapli/scrapligo#87]
Is there any way to get the prompt in `response.MultiResponse`?

Tried adding `opoptions.WithNoStripPrompt()` but no luck yet. While `GetPrompt()` can get the prompt, it would be nice to get exact prompt if a certain command in a long list to `SendConfigs` failed

**Comment by kellerza** [comment]
It seems the option should be set on SendConfigs (and not in NewPlatform!)

```
d.SendConfigs(data, opoptions.WithNoStripPrompt())
```

Thanks!!

**Comment by carlmontanari** [comment]
Hey @kellerza -- yep you got it -- it is kind of confusing and that is my fault, so sorry about that! but yeah, the idea is that any "platform" wide options live in options (just options) and apply to the driver as a whole, and the "operation" options live in "opoptions" and are applied on a per operation basis. HTH!
