### ISSUE TITLE
Support H3C and Huawei switches

### ISSUE THREAD

**Issue by longnehc** [scrapli/scrapligo#96]
I find that scrapligo already supports the cisco, arista, juniper, and nokia switches. Do you have any plan to extend the scrapligo to support the H3C and Huawei switches?

If not, can you tell me which file to modify and what test cases needed to be added to verify the correctness?

**Comment by carlmontanari** [comment]
Nope, you just need to make your YAML platform definition(s). You can find the "built in" ones [here](https://github.com/scrapli/scrapligo/tree/main/assets).
