### ISSUE TITLE
Support netconf driver in customized platform

### ISSUE THREAD

**Issue by longnehc** [scrapli/scrapligo#97]
Hi, recently I have made my YAML platform definition(s) to support the H3C switch. It works well in the CLI mode by using the SendInput and SendCommand interfaces.

I want to get a netconf driver in my self-defined platform and communicate the device via netconf. But it seems the platform only supports GetNetworkDriver() and GetGenericDriver(). Will you add the getNetconfDriver() in customized platform in the future?

BTW, I tried to modify the host, username and password in examples/netconf_driver/basics/main.go and run it. The output is "failed executing GetConfig; error: errTimeoutError: channel timeout sending input to device". 

After I checked the log in the switch, it successfully receives the hello request:
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability></capabilities></hello>

But the rpc request "<?xml version="1.0" encoding="UTF-8"?><rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="101"><get-config><source><running></running></source></get-config></rpc>]]>]]>" is treated as "XMLAGENT/6/XML_BAD_FORMAT: invalid xml format." from the device log.

**Comment by carlmontanari** [comment]
> Will you add the getNetconfDriver() in customized platform in the future?

No. You should almost certainly be changing nothing but creds/port when using netconf so no point in having netconf “platforms”.

Wrt to the rest, you will need to log and troubleshoot. Going to close this, but feel free to reopen if/when you have a verifiable bug with supporting information.

**Comment by longnehc** [comment]
> > Will you add the getNetconfDriver() in customized platform in the future?
> 
> No. You should almost certainly be changing nothing but creds/port when using netconf so no point in having netconf “platforms”.
> 
> Wrt to the rest, you will need to log and troubleshoot. Going to close this, but feel free to reopen if/when you have a verifiable bug with supporting information.


Hi, I debug using the python ncclient lib. The ncclient successfully gets the running configuration. The log in the ncclient side is 
<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:282a0a45-4118-4f70-b2f2-86c6a5536a0b">
<get-config><source><running/></source></get-config>
</rpc>]]>]]>

I add some breakpoint to get the netconf requests of scrapligo lib:
<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="101">
<get-config><source><running></running></source></get-config>
</rpc>]]>]]>
but get ""failed executing GetConfig; error: errTimeoutError: channel timeout sending input to device".

The log in the switch side is 
XMLAGENT/6/XML_REQUEST: netcontroler from xxxxx,session id 2,receive hello request.<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability></capabilities></hello>

XMLAGENT/6/HELLO: netcontroler from xxxx, session id 2,hello executed.

XMLAGENT/6/XML_BAD_FORMAT: invalid xml format.
