### ISSUE TITLE
Bare RPC example ?

### ISSUE THREAD

**Issue by mayuresh82** [scrapli/scrapligo#98]
Can you provide an example on how to execute a bare Netconf RPC in this new beta overhaul ? Used to be pretty straightforward prior to the overhaul. Thanks !

**Comment by carlmontanari** [comment]
Don’t think anything changed for rpc really, just it’s here now https://github.com/scrapli/scrapligo/blob/main/driver/netconf/rpc.go#L20

gunna close this unless. Feel free to reopen it there is a bug.
